feat: add types
ipfs/js-ipfs-repo pull request #275
Opened 2021-01-22 15:25 UTC by hugomrdias

Changes:

0c911f0 (Hugo Dias, 9 seconds ago)
   fix: fix possible undefined datastores

   - split datastore instantiation from opening
   -  add it-pushable types
   - add just-range types
   - add proper-lockfile types
   - fix lock.close we werent waiting for the promise

1fba61c (Hugo Dias, 24 hours ago)
   feat: base types

   - adds types
   - removes fake async
   - fixes tests for async errors that now are sync
   - adds local types for merge-options

2021-01-22 16:18 UTC, achingbrain requested changes

2021-01-22 16:18 UTC, achingbrain commented on src/types.ts
> +  storageBackends?: Partial<Record<Backends, DatastoreFactory>>
```suggestion
  storageBackends?: Partial<Record<Backends, { new(...args: any[]): Datastore }>>
```

2021-01-22 16:18 UTC, achingbrain commented on src/types.ts
> +  storageBackends: Record<Backends, DatastoreFactory>
```suggestion
  storageBackends: Record<Backends, { new(...args: any[]): Datastore }>
```

2021-01-22 16:18 UTC, achingbrain commented on src/types.ts
> +import type { DatastoreFactory } from 'interface-datastore'
```suggestion
import type { Datastore } from 'interface-datastore'
```

2021-01-22 19:14 UTC, achingbrain commented on types/merge-options/index.d.ts
> +export = mergeOptions
`merge-options` has types in v3, is this necessary?

2021-01-22 19:15 UTC, achingbrain commented on types/proper-lockfile/index.d.ts
> +declare function lock (file: string, options?: Options): Promise<release>
The smoking gun:

![image](https://user-images.githubusercontent.com/665810/105534950-218c2c00-5ce6-11eb-88d9-8ecb62c02d61.png)

Can these types not be added to `proper-lockfile`?

2021-03-04 19:45 UTC, hugomrdias commented
ready to go

2021-03-05 07:40 UTC, achingbrain approved these changes

2021-03-05 07:41 UTC, merged