Make blockstore identity-hash compatible
ipfs/js-ipfs-repo pull request #297
Opened 2021-04-07 12:04 UTC by hannahhoward

# Goals

Make the blockstore properly return blocks for "identity" CIDs (CID's where the multihash algorithm is "identity", meaning the contents of the hash are the actual data for the block, and there is no other data associated with the CID).

# Implementation

- Separate out typing for the blockstore interface
- Implement `idstore` based on https://github.com/ipfs/go-ipfs-blockstore/blob/master/idstore.go - this leaves the original blockstore implementation unchanged but adds a composable layer applied on top to add compatibility with identity hashes (served as the same blockstore interface)
- add `idstore` in construction of `repo.blocks`
- fix minor compatibility issues with `just-safe-get` and `just-safe-set` by fixing to patch release for now

# For discussion

I based implementation for delete and put operations on the go versions, which essentially treats a put or delete for an identity hash as a no-op. However, the golang version does not return the block itself for puts, and I wasn't sure whether I should be doing that. For now, I've made it so the identity block is included in the results of puts.

fix https://github.com/ipfs/js-ipfs/issues/3289

2021-04-07 12:49 UTC, achingbrain requested changes

2021-04-07 12:49 UTC, achingbrain commented on package.json
> +    "just-safe-get": "~2.0.0",
What was the error that meant this needed to change from `^` to `~`?

2021-04-07 12:49 UTC, achingbrain commented on src/idstore.js
> +  return createIdStore(blockstore)
Why not just export the `createIdStore` function?

2021-04-07 12:53 UTC, achingbrain commented
Nice work, thanks for submitting this.

To land this could you please open a PR against js-ipfs that depends on this PR as a gh dep and add tests for identity CIDs to the interface-ipfs-core suite?  At least for [dag.get](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/dag/get.js) and [block.get](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/block/get.js) but anywhere these code paths will be executed. 
 This will make sure it's tested against core, over http and that it behaves in the same way as go-IPFS (over http).

There's an overview of how to run the tests here: https://github.com/ipfs/js-ipfs/blob/master/docs/DEVELOPMENT.md#run-tests

2021-04-08 01:41 UTC, hannahhoward commented
@achingbrain I've responded to PR comments and reset the dependencies, resolving the breaking change in the latest `just-safe-get` / `just-safe-set` by fixing our calls to match the newly added types. A PR with tests to js-ipfs is incoming.

2021-04-08 03:58 UTC, hannahhoward commented
PR for js-ipfs to demonstrate fix: https://github.com/ipfs/js-ipfs/pull/3616

2021-04-14 14:40 UTC, achingbrain approved these changes

2021-04-14 14:40 UTC, merged